
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    data-password: hpdihpdi
    url: jdbc:mysql://47.104.25.139:3306/test?characterEncoding=utf-8&useSSL=false
server:
  port: 8081

